# Generated by Django 5.2.17 on 2026-08-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid')], default='active', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.borrower')),
            ],
        ),
    ]
