# Generated by Django 5.2.17 on 2026-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('active', 'Active'), ('repaid', 'Repaid')], default='active', max_length=20),
        ),
    ]
