# Generated by Django 5.2.17 on 2026-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_period',
            field=models.PositiveIntegerField(default=30, help_text='Repayment period in days'),
        ),
    ]
