# Generated by Django 5.2.17 on 2026-08-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_seed_loan_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_document',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='nin_documents/'),
        ),
    ]
