# Generated by Django 5.2.17 on 2026-08-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_loanapplication_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='repayment',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
