# Generated by Django 5.2.17 on 2026-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_repayment_confirmed_at_repayment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='transfer_reference',
        ),
        migrations.AddField(
            model_name='repayment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
